language: minimal

services:
  - docker

before_install:
  - docker image pull argovis/testdb:0.30
  - docker image pull redis:7.0.2
  - docker image pull argovis/api:2.6.0

script:
  - docker network create travis
  - docker container run -d --network travis --name database argovis/testdb:0.32
  - docker container run -d --network travis --name redis redis:7.0.2
  - docker container run -d --network travis --name api -e ARGOCORE=here -e ARGONODE=core  argovis/api:2.8.1
  - docker image build -t helpers:test .
  - docker container run --network travis helpers:test

